### ISSUE TITLE
No such course like calculus1 in coursera 

### ISSUE THREAD

**Issue by 12shivs** [P1xt/speedstudy#30]
In data science speedstudy guide, there is a coursera course link for a course calculus 1, upon clicking the link, coursera has no such course

**Comment by P1xt** [comment]
Ah, oops, I swapped the link in the other guides, must have missed it in data science.

**Comment by P1xt** [comment]
Yep, I'd swapped it in the main guides, but not in the speedstudy guides, should be all fixed now.
